### ISSUE TITLE
Oddities from the new release

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#72]
While playing the most recent incarnation of the game I noticed a couple minor issues/bugs.

- [x] Mouse has been enabled by default, but it's also still hidden by default making using the mouse difficult.
- [x] Tomb Golem weapons are floating next to the Tomb Golem. This is likely due to a naming oddity.
- [x] The Brawler job name has a unicode (U+2605) in it.
- [x] I thought Brawler was HP and EP for its upgrades. I see PA in there instead, was this intentional?
- [x] Do not default to the rest action, as it can be really easy to accidentally hit it. Note: This may have been my mouse, but I could not see it at the time. I think move works best as the default action.

Some cool things:
- I like how the job that gains the XP is listed in the post battle screen. I'm not 100% this is new, but this is the first time I noticed it.

**Comment by Moguri** [comment]
Move is the current default action. I'm hoping (and currently assuming) that your suspicion that your mouse was changing items is correct. I have also pushed 35a7ba57be5e987966032c8d05ee6d3e3dcb2d9a which will cause the menu to react only if the cursor is visible.

Doing HP and PA was intentional on the Brawler. I felt it better suited the class, but I am open to discussing this so I'm leaving that box unchecked for now.

Unicode U+2605 ("black star") is used to indicate the current class. However, after switching to DirectGUI our Unicode symbols do not appear to be displaying correctly. I have already switched learned abilities to `*` and I will do the same for the current class.

**Comment by ansmithf5** [comment]
Sounds good across the board. I am a little mixed on the PA for the brawler, but I can't think of any reason against it based on our current job flow.

I did have an idea that all jobs would branch from the Brawler, but that would make the name inaccurate and it is not our current configuration.

**Comment by TinySandwich** [comment]
Sounds good across the board. I am a little mixed on the PA for the brawler, but I can't think of any reason against it based on our current job flow.

I did have an idea that all jobs would branch from the Brawler, but that would make the name inaccurate and it is not our current configuration.

**Comment by Moguri** [comment]
I would prefer to have multiple base/starting jobs available to add more variety to starting golems. So, I am fine with making the Brawler an entry-level physical class.

When I first made the class, the MP gains were pretty useless for that tree, so I picked PA over MP. However, EP is now much more important. EP gain also seems like a very valuable upgrade, so does it make sense to give it to a basic class? The Ruinsmith is in a funky spot since it *is* a basic class that has EP upgrades since it used to have MP upgrades. Maybe we switch Ruinsmith to HP + MA as upgrades? Maybe Tactician (not yet implemented) can have EP upgrades since they need to keep a cool head, survey the battlefield, and react?

**Comment by TinySandwich** [comment]
WIth Ruinsmith and Brawler being the two base classes it'd make sense that they have some general upgrades. Perhaps they are as follows:

Brawler
HP Upgrades x3
PA Upgrades x2
EP Upgrades x1

Ruinsmith
EP Upgrades x3
MA Upgrades x2
HP Upgrades x1

**Comment by TinySandwich** [comment]
Though since Ruinsmith does come with spells/abilities we could remove some of the upgrades.

General rule of thumb could be each Job has 6 upgrades/abilities.

**Comment by Moguri** [comment]
I like the idea of sticking to 6 upgrades (stats or new abilities). I will do a run through the jobs and post a PR. We can tweak/expand this later as we get more abilities, but I think it will serve us well as a guideline for now.
